--- @enum RDBG_BREAKPOINT_KIND
RDBG_BREAKPOINT_KIND = {
	RDBG_BREAKPOINT_KIND_FUNCTION_NAME = 1,
	RDBG_BREAKPOINT_KIND_FILENAME_LINE = 2,
	RDBG_BREAKPOINT_KIND_ADDRESS = 3,
	RDBG_BREAKPOINT_KIND_PROCESSOR = 4,
}
